- name: Deploy Jenkins
  hosts: jenkins
  vars:
    jenkins_image: jenkins/jenkins:lts
  tasks:
    - name: Deploy the latest Jenkins container
      docker_container:
        name: jenkins_master
        image: "{{ jenkins_image }}"
        ports:
          - 8080:8080
        volumes:
          - /var/jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
    - name: Install tools
      shell: docker exec -u root jenkins_master apt-get update
    - name: Install tools
      shell: docker exec -u root jenkins_master apt-get install python-pip -y
    - name: Install tools
      shell: docker exec -u root jenkins_master pip install docker